# Change these first
owner: tderleth # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: thomasderleth.de
    url: https://thomasderleth.de/
    icon: https://thomasderleth.de/favicon.ico
  - name: www.cloudything.com
    url: https://www.cloudything.com/
    icon: https://www.cloudything.com/favicon.ico
  - name: tderleth.github.io/toolbox
    url: https://tderleth.github.io/toolbox/

status-website:
  baseUrl: /upptime
  logoUrl: https://thomasderleth.de/android-chrome-512x512.png
  favicon: https://thomasderleth.de/favicon-32x32.png
  themeUrl: https://tderleth.github.io/upptime/theme.css
  name: thomas derleth | upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
